### ISSUE TITLE
background segmentation effect not working on web

### ISSUE THREAD

**Issue by rktalusani** [DeepARSDK/quickstart-web-js#1]
i used the quickstart-web-js and tried loading the background segmentation from the "free masks" pack. I can see the galaxy background, but my video disappears from the canvas.

**Comment by SGoerzen** [comment]
same here

**Comment by Sikter** [comment]
Hi guys, background segmentation is currently not available on HTML5 SDK due to browser limitation to certain APIs we need to run deep learning models (SIMD API for example). However, we are making some progress in this department and I'm hopeful we will be able to share an HTML5 compatible segmentation soon.
